src/router.test.ts, src/router.ts
Hi!
I noticed you have a bug when there are multiple path parameters, so I fixed it and added a test. The issue was that `\{.*\}` is greedy, so `{abcd} {efgh}` was being parsed as `{` + `abcd} {efgh` + `}`.
=> Fix multiple path parameter handling

DOCS.md, README.md, src/backend.ts, src/router.test.ts, src/validation.test.ts, src/validation.ts
Closes #7
- Renamed OpenAPIRequestValidator => OpenAPIValidator
- Added validator.validateResponse
- Added validator.getRequestValidatorsForOperation
- Added validator.getResponseValidatorForOperation
- validator.validateRequest & validator.validateResponse now accept
operationId as second parameter
- OpenAPIBackend constructor opt validate can be a predicate function
to allow for fine control of whether to validate per request / operation
=> Implement response validation, add postResponseHandler

package-lock.json, package.json
- `reactstrap` - Unclear why it was here at all. Probably added by mistake.
- `@types/lodash` and `@types/swagger-parser` can be `devDependencies` as their types are not exposed to the consumer of the library (i.e. do not appear in the `openapi-backend`'s d.ts files).
=> Cleaned up unnecessary dependencies

package.json, tsconfig.json
The main reason is to use native async/await instead of down leveling to
provide better debugging experience.
1. Technically this is a breaking change. Maybe it needs a major version bump?
2. Probably need to mentioned somewhere in `README` or `DOCS` that library requires Node 8+. What would be a good place for it?
Fixes #26
=> Restrict to Node 8+

src/validation.test.ts, src/validation.ts
Names of the parameters were normalized, but names expected by 
the validator were not. This lead to failed validation, when OAS was 
specifying name of the header parameter not in lowercase.
=> Fixed validation for non-lowercase header parameters

src/router.ts, src/validation.test.ts
It was not working because [matching](https://github.com/anttiviljami/openapi-backend/blob/master/src/router.ts#L203) was happening against a prefixed path (e.g. `/v1/pets/42` against `/pets/{id}` given `apiRoot = '/v1'`).
I've implemented this to be a non breaking change. Alternative approach may be to make this part of the `normalizeRequest()` logic (see [this branch](https://github.com/devoto13/openapi-backend/tree/misc-improvements-alt)). Let me know if you prefer that approach.
=> Fixed path params validation with custom apiRoot

src/backend.ts
No functional change, only extracting the constructor options as an exported interface to simplify for clients that need a type to refer to.
For example, a client wanting to pass a subset of options currently would have to use constructs such as:
Pick<ConstructorParameters<typeof OpenAPI.OpenAPIBackend>[0], 'ajvOptions'>
but can now use 
Pick<OpenAPI.Options, 'ajvOptions'>
=> Extract constructor options as interface

src/backend.ts
In case we're running not in `quick` mode we're reading definition twice since it's already loaded and parsed.
This PR checks if `document` is already loaded and use it or read input document one more time to make `definition`.
=> Use loaded document to dereference

src/router.ts
**Issue:**
`Lets say` there are two operations with paths **_"/parties/{ID}/error"_** and **_"/parties/{ID}/{SubID}"_** exist in the openapi specification. The request with path **_"/parties/123/error"_** is not being matched with the correct operationId.
**Expected behaviour:**
The request path _"/parties/123/error"_ should be matched with _"/parties/{ID}/error"_
**Current behaviour:**
The request path _"/parties/123/error"_ is being matched with _"/parties/{ID}/{SubID}"_
**Fix**
The matched array can be sorted based on the number of variables in the path. The path with least number of variables can be picked up.
=> Refactored the orderBy function to find matching operation in router

src/backend.ts, src/types/swagger-parser.d.ts
Fixes the issue mentioned in https://github.com/anttiviljami/openapi-backend/pull/97#issuecomment-683420629. Specifying a base path is officially supported in `swagger-parser`, but their docs don't mention it. However, the type signature (https://github.com/APIDevTools/swagger-parser/blob/5f0c6250af5346d10bb2cd8533598a42f3cc73e5/lib/index.d.ts#L76-L78) does:
```ts
public dereference(api: string | OpenAPI.Document): Promise<OpenAPI.Document>; // used before
public dereference(baseUrl: string, api: string | OpenAPI.Document, options: SwaggerParser.Options): Promise<OpenAPI.Document>; // used now
```
=> Pass base path to dereference function

src/backend.test.ts, src/backend.ts
The handlers and securityHandlers objects passed to OpenAPIBackend's
constructor was stored as properties and later mutated (e.g. if registering
handlers separately). This could cause problems if passing a default set of
handlers to multiple instances of OpenAPIBackend, since it would then be
shared by all instances, hence overwritten with very confusing results.
Copying these objects instead to allow passing handlers objects that
aren't mutated, which also allows declaring them as constants (e.g. by using
Object.freeze).
=> Copy handlers passed to constructor instead of mutating passed objects

DOCS.md, jest.config.js, src/backend.ts, src/utils.ts, src/validation.test.ts, src/validation.ts
Closes #114
Adds new constructor option `lazyCompileValidators ` for OpenAPIValidator, which skips precompiling Ajv validators.
This gets applied when OpenAPIBackend is initialised with quick: true.
=> Add option to lazy compile Ajv validators

__tests__/resources/refs.openapi.json, src/validation.test.ts, src/validation.ts
Adds a function to clone and transform schemas before compiling them in Ajv which replaces circular references with JSON refs. Ajv will fail for schemas with recursive references because it stringifies them. However, Ajv will handle JSONSchema refs just fine.  
In reference to: #116
=> enables compiling recursive schemas with ajv

package-lock.json, package.json, src/backend.test.ts, src/backend.ts, src/router.test.ts, src/router.ts, src/types/openapi-schema-validation.d.ts, src/types/swagger-parser.d.ts, src/validation.test.ts, src/validation.ts
fixes #158
This is still draft, as it is waiting for new openapi-types: https://github.com/kogosoftwarellc/open-api/pull/757
Please review this, as this may be the version which will be future version in openapi-types.
This is not adding webhooks support to openapi-backend (if we would like to have such support i think this should be done in another task)
=> Add support for OpenAPI 3.1

package-lock.json, src/backend.test.ts, src/backend.ts, src/router.test.ts, src/router.ts, src/utils.ts, src/validation.test.ts, src/validation.ts
Since #212 has added support for openapi 3.1, openapi-backend types stopped working with openapi 3.0 types.
This PR ensures that both openapi 3.0 and 3.1 types are supported.
@anttiviljami please review this PR and check if everything works as expected
=> Ensure compatibility with openapi 3.0 and 3.1

src/validation.test.ts, src/validation.ts
Creates a null document validator, when the response is a 204 status code. This should fix #301 in which 204 responses without bodies are incorrectly failing response validation when also used with a default response.
=> Validation of a 204 response with an empty body

DOCS.md
As far as I can tell, the validation functions do not return promises, and there is no point in `await`ing them. Typescript was complaining about this.
=> Remove unneeded `await` from examples in DOCS.md

src/router.test.ts, src/router.ts
This is missing feature that does not work for example in AWS Lambda where the query parameters are inputted in query object from ALB Event's queryStringParameters object. Also AWS lambda passes the query parameters to the handler encoded so decoding must be done for the parameters.
=> feat: add support to pass array query parameters

src/backend.test.ts, src/backend.ts, src/router.ts, src/validation.ts
This change adds a new option 'coerceTypes' that will enable coerce typing of request query and path parameters. It is off by default and can be enabled if validate is also enabled.
Fixes #554 and supersede #571.
=> Add option to enable coerce types

src/backend.test.ts, src/backend.ts
Adds:
- preRoutingHandler
- postRoutingHandler
- postSecurityHandler
- preOperationHandler
Updated docs here:
https://openapistack.co/docs/openapi-backend/request-lifecycle/
=> Add lifecycle handlers
